[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "markdown>=3.7",
    "pelican>=4.11.0",
    "pelican-simple-footnotes>=1.0.3",
]
