name: Publish Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch entire history
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican ghp-import markdown pelican-simple-footnotes pelican-share-post
      
      - name: Generate Site
        run: |
          pelican content -s publishconf.py
      
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          ghp-import -n output -b gh-pages -f
          git push -fq https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages:gh-pages